package com.bottrading.service.risk;

public enum RiskFlag {
  DAILY_LOSS,
  DRAWDOWN,
  API_ERRORS,
  WS_RECONNECTS,
  TRADE_LIMIT,
  TRADE_SIZE,
  ANOMALY_SLIPPAGE,
  ANOMALY_FILL_RATE,
  ANOMALY_QUEUE_TIME,
  ANOMALY_LATENCY,
  ANOMALY_API_ERRORS,
  ANOMALY_WS_RECONNECTS,
  ANOMALY_SPREAD
}
