ALTER TABLE positions
    ADD COLUMN IF NOT EXISTS side VARCHAR(10),
    ADD COLUMN IF NOT EXISTS trailing_stop NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS trailing_offset NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS breakeven_price NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS oco_group_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS entry_atr NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS last_adjustment_at TIMESTAMP;
