ALTER TABLE positions
    ADD COLUMN IF NOT EXISTS qty_init NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS qty_remaining NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS take_profit NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS trailing_conf TEXT,
    ADD COLUMN IF NOT EXISTS last_update_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(120),
    ALTER COLUMN status TYPE VARCHAR(20),
    ALTER COLUMN status SET DEFAULT 'OPENING';

ALTER TABLE managed_orders
    ADD COLUMN IF NOT EXISTS stop_price NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS exchange_order_id VARCHAR(120);

ALTER TABLE managed_orders
    ALTER COLUMN status TYPE VARCHAR(20);

ALTER TABLE trades
    ADD COLUMN IF NOT EXISTS position_id BIGINT REFERENCES positions(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS fee NUMERIC(18,8),
    ADD COLUMN IF NOT EXISTS executed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS side VARCHAR(10);
